{% set version = "0.9.0" %}

package:
  name: spectrum
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spectrum/spectrum-{{ version }}.tar.gz
  sha256: 4539347e7cdb9ea4ea63ca76033eed8bf54f283dc4a42e966464734c279809cd

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  imports:
    - spectrum
    - spectrum.mtm  # test the C extension import

about:
  home: http://github.com/cokelaer/spectrum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spectrum Analysis Tools
  doc_url: http://pyspectrum.readtedocs.io/en/master
  dev_url: http://github.com/cokelaer/spectrum

extra:
  recipe-maintainers:
    - cokelaer
    - pauldmccarthy
