{% set version = "0.7.3" %}
{% set name = "spectrum" %}
{% set sha256 = "212bc7d01d94bde1cbced5dfc458e1a630e60ed8bde0626641ec48b1c2e154e9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools
    - toolchain

  run:
    - python
    - numpy
    - scipy
    - matplotlib # not required anymore strictly speaking but let us install it for conda

test:
  imports:
    - spectrum
    - spectrum.mtm # test the C extension import

about:
  home: http://github.com/cokelaer/spectrum
  license: "BSD 3-clause"
  license_family: BSD
  license_file: LICENSE
  summary: 'Spectrum Analysis Tools'
  doc_url: http://pyspectrum.readtedocs.io/en/master
  dev_url: http://github.com/cokelaer/spectrum

extra:
  recipe-maintainers:
   - cokelaer
