{% set version = "0.7.5" %}

package:
  name: spectrum
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/s/spectrum/spectrum-{{ version }}.tar.gz
  sha256: ae88d51d9b7b9d0a9b0bd8aaef95265cce0c9b21bee1c847a769e60fa0ede870

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  imports:
    - spectrum
    - spectrum.mtm  # test the C extension import

about:
  home: http://github.com/cokelaer/spectrum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spectrum Analysis Tools'
  doc_url: http://pyspectrum.readtedocs.io/en/master
  dev_url: http://github.com/cokelaer/spectrum

extra:
  recipe-maintainers:
   - cokelaer
