{% set version = "0.8.0" %}

package:
  name: spectrum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spectrum/spectrum-{{ version }}.tar.gz
  sha256: 51d4c6987eab1a933c801adebe79736d775ea95e6f6d635c3c997bd57a288433

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  imports:
    - spectrum
    - spectrum.mtm  # test the C extension import

about:
  home: http://github.com/cokelaer/spectrum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spectrum Analysis Tools
  doc_url: http://pyspectrum.readtedocs.io/en/master
  dev_url: http://github.com/cokelaer/spectrum

extra:
  recipe-maintainers:
    - cokelaer
