{% set version = "0.8.1" %}

package:
  name: spectrum
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spectrum/spectrum-{{ version }}.tar.gz
  sha256: c5c262f0a67d6013b5503749d6e9fdfe5909d10b45c85e391df001ed112fd8ff

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  imports:
    - spectrum
    - spectrum.mtm  # test the C extension import

about:
  home: http://github.com/cokelaer/spectrum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Spectrum Analysis Tools
  doc_url: http://pyspectrum.readtedocs.io/en/master
  dev_url: http://github.com/cokelaer/spectrum

extra:
  recipe-maintainers:
    - cokelaer
