# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SXdJeAUo3txPTTav51xiFsoC3H4QdQXOoKWLjqnkmGR7GicOX7e5K+/QPboLHaC1FAX7uLkG6IGsEKoGI49O07tFReyqY0rVPYRg0THfaH+82ZFVMLXOgZPgnkaoWI4zPt+fC8qmzYd0mf53QEAcN8i7yZRagwWOjI+XSY9xgs8re/Vfhzhiou7I77qNuTB4lf8x2eqTzsDEQV6+fCjQlbS2P5urvImldUXRS20DcUOEvO4Ajzh9clIGsTMQ+1E3WRvctXym0bOjh7l7IZfKE/9CC/LqGdO7NTPcm5XZDTnRaoSOARuxDA3ldX0EIty7z8Cnyd6Fv+nahKKcZWYGPz77tjpDrNjaQxVUD/Xfts4AH3FFqHtYk5zghqX+XCuzW+pkMQ5kVV0gYVB71rE6zzL9Q3lR52xkXaL3iLcASvbCXllJkRPIEwkvj3zFzqoWd+Cu48dgtYd7YPqwoy7tnjI218BxcrgOxjNYJFauGNv3HdjwlhohpaU1xnhaqBqxeGZtqXk1j2yMpoJL3Ka7wQ1M9faXRxEQl91FCk6oT4SkCxqg7DJkv2lAgAXZRKa/T0R4rjFONg4X3tLv/fnwPxAqFM3PdIT3xSP2lu0/zuDYwZvZ5UJDnBse8EGwnD2d8fUrjImcpwGLZmH4RMtCt92wJ09M/lASyrjZHxPYaLE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
