travis:
  secure:
    BINSTAR_TOKEN: e3mfLq4nu+60nLInqx/5xzQv6msO7UmrH9lDbdNmgefvh3T1DRkAu0s2zh+8X+4uoJ7ttlC2oshVT7PdYoiKiZ2PeHo/2erATNTm0L8onXEEoqkBUE11h/SbueztXIH/h00TZV9OWt5mi+78+yICy8wBgBOwNq1u2t3hGBgoco+3+bbcxrwWZvW8zKRVeHiP4LvKNNg+iS36mfCjzzz4ZyZvExlgDeLfOUlzafc7KeqKBXOSTUd+IZ+5aFunwzAp5vygNRDR0/p5bf/z/+fOxpggtPmPON7426YsKkwBOk4XxtDahZJwIiK4H4Hka4eoTwKcld61od1s1igx70M367A9TTg7Sv0RGS9YJqMyXy91Cole/NtNPxgB397vqCOVN6VIefBDwAH+iDwfLVtIA/JjvlIniPEvsg3IkX0BY3H7x46NzFBtnkBVj4geX/eJ50gHv7YWqsBaRFhqYT/KC7AfbWQD6+002fDc03k0MPOWSoCK1VmMxueMcYh2cxOkn/JpSeOIJghhuLIm7dUaGQB+ip8MRhI097EPLAZ39BqgN+n9ZOStU2o/huITNm3JGcOtufL7cMo0XuP1Ilh+tn5dTZ4NNyVQM+YxDPvGym86jzegLDcXkY0IafxJFOJdZBmiB5dRiMoT76Dqp9gRzD4l5JRDEjlgwlBmTTzhLOc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
