travis:
  secure:
    BINSTAR_TOKEN: ZKwviMMnMqXm4EHtMp5enz0alNLM71dOfWYF6RCR9TgMJeM3uvPbhk9Tmmiza/zcRf+ZbxRyG9jEyBhWdwBs0chvzP7l5jkCK/4B0abNoQWvlehD1c698/3kg/XD8eaI70M/pz/dn96o5mNpCO+lKBZKkOTRHB2P6uviCgQzLNZJUCOH6Git/N0wlG712hWsmjW9BCSJM8Zhsq05UFdoCIqapDZ1pukwAXdt3d0fTWrAf1crGyOBwvZujEbbDQl/2PnZy4LyvTI6mhyx5RfRlN6ckXCF5itmJTTv/6fz41epwXhnOub5WmOUw0aJet2g21hegfX+c3AdNZglLPVygLHBiQh1k87CiIDjp+3R2aKDjvQr2+jdu7RSWodauZzxlLXd94RD27ar8XgeY8DcWt/7SWb3sff7hKirczMlVEWMV8NtisLpWrQv8JZoce0aMKrEwKqZNgdMonSL2OHAc5l7ERcnYSUlfdUFJRb4m3kaobZp+o2laRjzzrz6eq30rPDaPis3VsjYQg3rM/x7AWttQEX6Aq2zUEZ2jEXWqPFUWhUc7OhMnoBQbus1DLPxOF1oTSjlAvb8+0rqCxsYdahnMOi3wwTrGiUEHxjZKk7LqMulb6IZzPWLBLEq8h+U4mxjGVtP7/FP1Orph80YjMZj6wJHQ3drvwLkyQX5fqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
