travis:
  secure:
    BINSTAR_TOKEN: WzAcQwdONYA4DudL1OkhZTpKjTCeb7AaH4Xh+KJjdbakYJUSP3aE5LADIX3qmI+MCHdiTVuELhMOMjrhimlSCvl7jUEE8HSgMBYWJNBI5eOxRPkYBKYNDb6XZ87bsi1S+YlBMngGaQfGDFs5yW2d8FnRaykWfbLemBm4ja5ptK1EzTMNIcGkHNjpZcCVhddUmwP4WZKB3APJM8vGS7vg+SuGqmLiKgzW/Xbh3xJVdgLr05Eq9l3cEC8yGdEmZNA68keqrXTOBMRexKr6eLj7hcOUIKykydQxKV7gQMdE49e+zsS+wkSBJH3l6BR5Z9EvodPmUvcHifeSeH63wMUX5h4yUj4TQ7hy+SvnX+uSTMrQIy4sZVeDnZIf9h5nKRU1FZhXlQi72V1J5xi6jA3xai/TRiYicvv1JI1bcDqTeTZrs6bdvj6HJNo2wmasJ9I0mhIgIkCT5cEXlskN4AlfftAGw7wuwhKl0JTX1Ht2s7pwWgJA/ZCgObvGB5GTpCtG1GYR0Qk2fMJOa8htv8D+YTz8gcXUUkak8B67h9wWE74eKU92YEveXkOLjOCjic9FUA8iX0MsAdOpQRLcTo7p5YBxBvvKGK20K/s8EHHxNsQ2eMyDu9szCwo8gbLuJiX9Fu7V73ZNGYbvsRy8MskKk2teRtibSGnlpg9qMUj38FA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
