travis:
  secure:
    BINSTAR_TOKEN: RPSsu4Km+OZMhMGUdH0gAF/D4Se30YhKSg2Qfne3fkMUGp9n8C8lJaZFCB8nbSRNfAvQk4l3JSxTm8snjHPOU2vgdww4BchYteJrnEiL/GmreQLfOPm43xXSVUr8Cnu+Vl4owmwdz1IkJe80Hlx73i3at+vWK+SlWzfx2sHPPRRn+Jrz2xv01BigHpuznIB1FJc2v5V/xWw6FmUX6QOR74+6eHol9IWLQfzybYJha8ACD0SRgeA9KiRNjrubyv1CcMHAJHVAzPS6twv0rHhWx5ZRjNkiimrNlKyXhQy1C5G0FgghUIqy9Tf26TcmFdTgcFWJh3srOMjJ1f24jQXIxYJYWC0APKhqfZDd5B2aTMTclJPI+yZI/4Z2d8H2TVcd9a4fVs3THHqOIzJ1o7Z7OAGI3Npr6bC98pNbuUFPg6M0uhWhN9OAjtnp2XpgjljMIBujTBQbS/kpaw4bjY3iGQn9MuzzWr47rMm66rFhREQGqc368k5B5Y/24q5CiQYorElw2CTDQe1VCCg0YRCBRMC6ZANF33z6e71WrgtINpy5b3ieeRr0nUHxZLXXRzDOPxWxpzRlLycLxwfo6WxnjvOB85ICI5exKessFvowRuL/Ol8LWKr10R+gvlCzBfdYFhO4TT8R0TwtoKdy4KQA1Kv5f7tD4lDqUl4V3ge1Bk8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
