travis:
  secure:
    BINSTAR_TOKEN: SXdJeAUo3txPTTav51xiFsoC3H4QdQXOoKWLjqnkmGR7GicOX7e5K+/QPboLHaC1FAX7uLkG6IGsEKoGI49O07tFReyqY0rVPYRg0THfaH+82ZFVMLXOgZPgnkaoWI4zPt+fC8qmzYd0mf53QEAcN8i7yZRagwWOjI+XSY9xgs8re/Vfhzhiou7I77qNuTB4lf8x2eqTzsDEQV6+fCjQlbS2P5urvImldUXRS20DcUOEvO4Ajzh9clIGsTMQ+1E3WRvctXym0bOjh7l7IZfKE/9CC/LqGdO7NTPcm5XZDTnRaoSOARuxDA3ldX0EIty7z8Cnyd6Fv+nahKKcZWYGPz77tjpDrNjaQxVUD/Xfts4AH3FFqHtYk5zghqX+XCuzW+pkMQ5kVV0gYVB71rE6zzL9Q3lR52xkXaL3iLcASvbCXllJkRPIEwkvj3zFzqoWd+Cu48dgtYd7YPqwoy7tnjI218BxcrgOxjNYJFauGNv3HdjwlhohpaU1xnhaqBqxeGZtqXk1j2yMpoJL3Ka7wQ1M9faXRxEQl91FCk6oT4SkCxqg7DJkv2lAgAXZRKa/T0R4rjFONg4X3tLv/fnwPxAqFM3PdIT3xSP2lu0/zuDYwZvZ5UJDnBse8EGwnD2d8fUrjImcpwGLZmH4RMtCt92wJ09M/lASyrjZHxPYaLE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
